"""patient profile: entry provenance, soft-remove, patient_medication

Additive only, hand-written (never autogenerated — the shared tables are not
this repo's to recreate). It:

1. Adds provenance and soft-remove columns to the shared `allergy` table
   (`recorded_by`, `updated_at`, `removed_at`).
2. Adds provenance columns to the shared `chronic_condition` table
   (`recorded_by`, `recorded_at`, `updated_at`). A condition is taken off the
   list by `status='resolved'`, so it needs no `removed_at`.
3. Creates `patient_medication`, owned outright by this repo.
4. On Postgres only, enables RLS on `patient_medication` with policies that
   mirror the shared tables, so the new table is not readable through the
   Supabase Data API. (This app connects with BYPASSRLS and scopes every
   query itself; the policies protect the *other* door.)

Revision ID: 488dbf2b3915
Revises: 6feacefae2d0
Create Date: 2026-09-23 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "488dbf2b3915"
down_revision: str | Sequence[str] | None = "6feacefae2d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _recorded_by() -> sa.Column:
    return sa.Column(
        "recorded_by",
        sa.Uuid(),
        sa.ForeignKey("user_profile.user_id", ondelete="SET NULL"),
        nullable=True,
    )


def upgrade() -> None:
    # 1. allergy (shared)
    op.add_column("allergy", _recorded_by())
    op.add_column("allergy", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("allergy", sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True))

    # 2. chronic_condition (shared)
    op.add_column("chronic_condition", _recorded_by())
    op.add_column(
        "chronic_condition",
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.add_column(
        "chronic_condition",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 3. patient_medication (repo-owned)
    op.create_table(
        "patient_medication",
        sa.Column(
            "medication_id",
            sa.Uuid(),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "patient_id",
            sa.Uuid(),
            sa.ForeignKey("patient.patient_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("strength", sa.String(50), nullable=True),
        sa.Column("frequency", sa.String(50), nullable=True),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        _recorded_by(),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("idx_patient_medication_patient_id", "patient_medication", ["patient_id"])

    # 4. RLS (Postgres only — the helper functions live in Supabase's `public`).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE public.patient_medication ENABLE ROW LEVEL SECURITY")
        op.execute(
            "CREATE POLICY patient_medication_select ON public.patient_medication "
            "FOR SELECT USING ("
            "patient_id = my_patient_id() "
            "OR doctor_has_patient_access(patient_id) "
            "OR is_admin())"
        )
        op.execute(
            "CREATE POLICY patient_medication_write ON public.patient_medication "
            "FOR ALL USING (patient_id = my_patient_id() OR is_admin()) "
            "WITH CHECK (patient_id = my_patient_id() OR is_admin())"
        )


def downgrade() -> None:
    # Exact reverse of upgrade(). WARNING: destroys every patient_medication
    # row and all allergy/condition provenance and soft-remove markers.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS patient_medication_write ON public.patient_medication")
        op.execute("DROP POLICY IF EXISTS patient_medication_select ON public.patient_medication")

    op.drop_index("idx_patient_medication_patient_id", table_name="patient_medication")
    op.drop_table("patient_medication")

    op.drop_column("chronic_condition", "updated_at")
    op.drop_column("chronic_condition", "recorded_at")
    op.drop_column("chronic_condition", "recorded_by")

    op.drop_column("allergy", "removed_at")
    op.drop_column("allergy", "updated_at")
    op.drop_column("allergy", "recorded_by")
