"""auth hardening: authority-column guards + case-insensitive unique email

Additive only, hand-written (never autogenerated). Closes audit findings C1
and H2: the shared schema's RLS policies let a signed-in user UPDATE their
own `doctor` / `user_profile` / `patient` row through the Supabase Data API,
including columns this app treats as authoritative. RLS is row-level only, so
the guard has to be column-aware — BEFORE triggers that refuse changes to
those columns unless the writer is privileged.

"Privileged" (`cn_is_privileged_writer()`) means any of:

* a database role other than `anon`/`authenticated` — this app connecting as
  `postgres`, `service_role` through PostgREST, and the SECURITY DEFINER
  `handle_auth_user_*` sync triggers (which run as their owner);
* a request whose JWT role is `service_role`;
* `public.is_admin()` — so admin verification of doctors keeps working, exactly
  as the existing `doctor_update_own_or_admin` policy already intends.

The helper and trigger functions are deliberately SECURITY INVOKER: inside a
SECURITY DEFINER function `current_user` would be the owner, and every caller
would look privileged.

It also adds `uq_user_profile_email_lower` — case-insensitive unique email
on `user_profile` (`email` is nullable; NULLs don't collide). Verified clean
before writing this: 0 case-insensitive duplicates.

Deliberately NOT added: a partial unique index for active consent grants.
An "active" grant is unrevoked AND unexpired (consent BL-05/BL-12), and an
index predicate cannot reference `now()` — `WHERE revoked_at IS NULL` would
make an expired-but-unrevoked grant block a new one, changing a consent
business rule. The grant race is closed with a patient-row lock in
`consent/service.py` instead.

Postgres only — the SQLite test database gets the index from the model
metadata instead, and has no Data API to guard. The SQL lives in module-level
constants so `tests/test_pg_authority_guards.py` can run exactly this SQL
against a real Postgres.

Revision ID: a3c1f0e7b2d4
Revises: 488dbf2b3915
Create Date: 2026-10-08 12:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3c1f0e7b2d4"
down_revision: str | Sequence[str] | None = "488dbf2b3915"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PRIVILEGED_WRITER_FN = """
CREATE OR REPLACE FUNCTION public.cn_is_privileged_writer()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT current_user NOT IN ('anon', 'authenticated')
      OR COALESCE(auth.role(), '') = 'service_role'
      OR public.is_admin();
$$;
"""

DOCTOR_GUARD_FN = """
CREATE OR REPLACE FUNCTION public.cn_guard_doctor_authority()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.cn_is_privileged_writer() THEN
    RETURN NEW;
  END IF;
  IF TG_OP = 'INSERT' THEN
    -- Self-registration may create a doctor *account*, never doctor *access*.
    IF NEW.verification_status IS DISTINCT FROM 'pending'
       OR NEW.verified_by IS NOT NULL
       OR NEW.verified_at IS NOT NULL THEN
      RAISE EXCEPTION 'doctor verification can only be set by an administrator'
        USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
  END IF;
  IF NEW.verification_status IS DISTINCT FROM OLD.verification_status
     OR NEW.verified_by IS DISTINCT FROM OLD.verified_by
     OR NEW.verified_at IS DISTINCT FROM OLD.verified_at
     OR NEW.pmdc_number IS DISTINCT FROM OLD.pmdc_number
     OR NEW.user_id IS DISTINCT FROM OLD.user_id THEN
    RAISE EXCEPTION 'doctor verification, PMDC number and owner can only be changed by an administrator'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;
"""

USER_PROFILE_GUARD_FN = """
CREATE OR REPLACE FUNCTION public.cn_guard_user_profile_authority()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.cn_is_privileged_writer() THEN
    RETURN NEW;
  END IF;
  -- email is synced from auth.users by handle_auth_user_update (privileged);
  -- lockout counters and the synthetic-data flag are the app's alone.
  IF NEW.email IS DISTINCT FROM OLD.email
     OR NEW.is_synthetic IS DISTINCT FROM OLD.is_synthetic
     OR NEW.failed_logins IS DISTINCT FROM OLD.failed_logins
     OR NEW.locked_until IS DISTINCT FROM OLD.locked_until THEN
    RAISE EXCEPTION 'email, lockout and synthetic-data fields cannot be changed directly'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;
"""

PATIENT_GUARD_FN = """
CREATE OR REPLACE FUNCTION public.cn_guard_patient_authority()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.cn_is_privileged_writer() THEN
    RETURN NEW;
  END IF;
  -- The Medical Passport number is issued once and never changes (FR1).
  IF NEW.passport_uid IS DISTINCT FROM OLD.passport_uid
     OR NEW.user_id IS DISTINCT FROM OLD.user_id THEN
    RAISE EXCEPTION 'passport number and owner cannot be changed directly'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;
"""

# One statement per entry: Alembic's async env (asyncpg) cannot run a
# multi-statement string in a single `op.execute`.
TRIGGERS: tuple[str, ...] = (
    """CREATE TRIGGER cn_guard_doctor_authority
  BEFORE INSERT OR UPDATE ON public.doctor
  FOR EACH ROW EXECUTE FUNCTION public.cn_guard_doctor_authority();""",
    """CREATE TRIGGER cn_guard_user_profile_authority
  BEFORE UPDATE ON public.user_profile
  FOR EACH ROW EXECUTE FUNCTION public.cn_guard_user_profile_authority();""",
    """CREATE TRIGGER cn_guard_patient_authority
  BEFORE UPDATE ON public.patient
  FOR EACH ROW EXECUTE FUNCTION public.cn_guard_patient_authority();""",
)

INDEXES: tuple[str, ...] = (
    "CREATE UNIQUE INDEX uq_user_profile_email_lower ON public.user_profile (lower(email));",
)

UPGRADE_STATEMENTS: tuple[str, ...] = (
    PRIVILEGED_WRITER_FN,
    DOCTOR_GUARD_FN,
    USER_PROFILE_GUARD_FN,
    PATIENT_GUARD_FN,
    *TRIGGERS,
    *INDEXES,
)

DOWNGRADE_STATEMENTS: tuple[str, ...] = (
    "DROP INDEX IF EXISTS public.uq_user_profile_email_lower;",
    "DROP TRIGGER IF EXISTS cn_guard_patient_authority ON public.patient;",
    "DROP TRIGGER IF EXISTS cn_guard_user_profile_authority ON public.user_profile;",
    "DROP TRIGGER IF EXISTS cn_guard_doctor_authority ON public.doctor;",
    "DROP FUNCTION IF EXISTS public.cn_guard_patient_authority();",
    "DROP FUNCTION IF EXISTS public.cn_guard_user_profile_authority();",
    "DROP FUNCTION IF EXISTS public.cn_guard_doctor_authority();",
    "DROP FUNCTION IF EXISTS public.cn_is_privileged_writer();",
)


def upgrade() -> None:
    if op.get_context().dialect.name != "postgresql":
        return
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    if op.get_context().dialect.name != "postgresql":
        return
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
